formatter: "" # this is required

version: ""

header-from: .terraform-docs/terraform-docs-header.md
footer-from: .terraform-docs/terraform-docs-footer.md

sections:
  hide: [resources, requirements, providers, modules]
